hold_on:
  name: Temperature Hold On
  description: Instruct the NeoStat or NeoStats specified to 'hold' a specified temperature for a specified period of time.
  target:
    entity:
      integration: heatmiserneo
      domain: climate
  fields:
    hold_duration:
      name: Hold Duration
      description: Set the duration for the hold (hh:mm:ss).
      default: "01:00:00"
      example: "01:00:00"
      selector:
        duration:
    hold_temperature:
      name: Temperature
      description: Set the target temperature to hold.
      default: 20
      example: 20
      selector:
        number:
          min: 7
          max: 35
          step: 0.5
          unit_of_measurement: °
hold_off:
  name: Temperature Hold Off
  description: Return the NeoStat(s) to its default state (Auto or Standby).
  target:
    entity:
      integration: heatmiserneo
      domain: climate
timer_hold_on:
  name: Timer Hold On
  description: Instruct the NeoStat in TimeClock mode or NeoPlug to 'hold' for a specified period of time.
  target:
    entity:
      integration: heatmiserneo
      domain: select
  fields:
    hold_duration:
      name: Hold Duration
      description: Set the duration for the hold (hh:mm:ss).
      default: "01:00:00"
      example: "01:00:00"
      selector:
        duration:
    hold_state:
      name: Hold State
      description: Whether we should hold on or off
      default: true
      selector:
        boolean:
set_away_mode:
  name: Set Away Mode
  description: Set Away/Holiday Mode on the Heatmiser NeoHub
  target:
    entity:
      integration: heatmiserneo
      domain: binary_sensor
  fields:
    away:
      name: Away State
      description: Whether to set away on or off
      default: false
      example: true
      selector:
        boolean:
    end:
      name: Holiday End
      description: Optional end date for holiday mode
      required: false
      example: "2024-01-01 00:00:00"
      selector:
        datetime:
