name: Create release package

# yamllint disable-line rule:truthy
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/${{ steps.version.outputs.version }}/' custom_components/heatmiserneo/manifest.json

          cd custom_components/heatmiserneo
          zip ../../heatmiserneo.zip -r ./
      - uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./heatmiserneo.zip application/zip
