name: Validate with hacs

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    name: "HACS validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"
      - name: "validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
